### ISSUE TITLE
FAN ONLY Mode Fails with RECOVAIR

### ISSUE THREAD

**Issue by MisfitPunisher** [thomasgermain/vaillant-component#160]
Hi firends,

I have installed a VRC 700 system that controls The hotwater, heating, cooling, and a RECOVAIR.

The recovair appears as a FAN, which I can chose the running mode, but not the speed.

By mistake this night I pressed the FAN ONLY mode on the heating card, and the RECOVAIR start to run at full throttle.

When I stopped the FAN ONLY mode on the heating card the RECOVAIR has not stopped, and It did not appear as working on full throttle on the Vaillant APP. 

Thank you all.

**Comment by thomasgermain** [comment]
Hello

>The recovair appears as a FAN, which I can chose the running mode, but not the speed.
From HA point of view, speed is deprecated, it has been replaced by percentage. I decided to not allow to set speed (nor percentage) because of the "incoherence" between HA and vaillant:
- from HA point of view, set_speed (or set_percentage) service means: I want my fan to operate right now at X speed/percetange
- from vaillant point of view, this is a bit different since you cannot directly set the speed, but rather set the speed for a given mode (DAY/NIGHT AUTO). So it can lead to awkward situation: the fan is in DAY mode and you set the speed. Which speed should it change ? DAY or NIGHT mode ?

Also, there are multimatic services to do so:
- multimatic.set_ventilation_day_level
- multimatic.set_ventilation_night_level


> When I stopped the FAN ONLY mode on the heating card the RECOVAIR has not stopped, and It did not appear as working on full throttle on the Vaillant APP.

So, setting FAN ONLY mode sounds to work as expected (fan at full throttle and it stops the heating). 

Now, how did you stop the FAN ONLY ? Which mode did you select on the heating card ? It sounds like mutimatic app understood what the integration ask (to stop FAN ONLY mode).
How did you eventually stop the fan ?

Do you have any error in the log ?

Thomas
