### ISSUE TITLE
Would you consider supporting HACS?

### ISSUE THREAD

**Issue by emresumengen** [thomasgermain/vaillant-component#17]
Just as an idea 😃 

Or of course even better to have it integrated directly/natively into HA itself.

**Comment by thomasgermain** [comment]
Dammed you're in my head, i'm just writing down some analysis :smiley:

**Comment by emresumengen** [comment]
> Dammed you're in my head, i'm just writing down some analysis 😃
> But as usual, the doc is not really helpful, so I have to figure out what is the difference with HVAC_MODE

Wish I could help, but very rusty as a programmer 😃 

But, let me know if there are things I can test (have a test docker environment so I can definitely try my best). I’m still pending the vSmart Controller to be installed by the service though...

**Comment by thomasgermain** [comment]
I tried locally, but as far as I can see, there is nothing special...
I set my zone to heat (DAY mode), so the HA HVAC mode is HEAT, here is what I got:
![image](https://user-images.githubusercontent.com/12560542/89415833-bd23e300-d72c-11ea-9379-be23cf7f5935.png)

So it says the zone is in heating mode (orange color) but since it doesn't actually heat, it also says "Inatif" (inactive in English).

By the way, I can only introduce it for zones, not for rooms (room = a room managed by ambisense)
