### ISSUE TITLE
More info on VR921 compatibility?

### ISSUE THREAD

**Issue by hvbargen** [thomasgermain/vaillant-component#190]
I know that the readme explicitly says it is not compatible to VR921.
Can you explain this a little more detailed?

I mean, it seems that the SensoApp contacts the same REST API (v4) as seen in the code of pymultimatic, which is the technical basis for this code.

So it seems it should be possible to make this work with VR921 using this code as a starting point!?

I own a VWL 75/6A and VR921 since a few weeks and I'm looking for a way to at least "see" it from HA.

I see 5 possible ways:

Pure local connections, not depending on the cloud:
1) Maybe modbus? Vaillant sells extra hardware, but quite expensive and probably  not compatible.
2) EEBUS: According to an expert, the VR921 EEBUS support doesn't fulfill the specs. I am able to connect, but the VR921 doesn't announce its Use Cases as it should.
3) eBus (the wire protocol which the devices use for their communication): One needs extra hardware, which is inexpensive, but not deliverable ATM. I pre-ordered one. This seems to be the most promising approach.
 Connections and depending on the cloud:
4) This project.
5) Get access to the official API documentation. I tried to sign in to the Vaillant developer programme, but ATM this is restricted to business partners. They told me to be patient as this may change soon.

**Comment by thomasgermain** [comment]
The multimatic app can actually use 2 APIs. The multimatic API and the senso API.

API are quite similar, but still different. As far as I can see, the authentication is the same, some API URLs are the same, but responses are different.

There are 2 (main) reasons why there is no support (yet) for senso;
- My system is not compatible with senso, so not possible to test what I'm doing. API are not documented :)
- Multimatic API (I don't know for senso API, but I guess it's the same) is really "poor", or  misleading. Let's have an example: calling the API for a zone. According to the API response, the zone should heat (because current temperature is below the target temp). But then, we call the "quick mode" API and we realize there is a quick mode running (for example "one day away"). Given both API response we should conclude that the zone is not heating because the quick mode take precedence over the zone settings. The underlying connector (https://github.com/thomasgermain/pymultiMATIC) is actually doing the kind of computations. Since there is no doc, I tested it myself with my installation, by playing with the API and analyzing the results. So In order to the integration to be compatible with senso, this work should be done for senso API.


> So it seems it should be possible to make this work with VR921 using this code as a starting point!?

Yes this is certainly possible, see https://github.com/thomasgermain/pymultiMATIC/pull/100, a PR is ongoing to add initial support for senso.

About non-cloud solutions:
1. I have no clue there is a modbus module
2. Yeah, I guess EEBUS sounds beautiful, but I guess each company has its own variant
3. I think this is a reasonable solution (see https://github.com/john30/ebusd-configuration anf https://fromeijn.nl/connected-vaillant-to-home-assistant/)
4. If senso support is added, this is a possible solution. 
5. I also ask and I received the same response :/
6. Extra point, myVaillant *should* provide new API (and unify senso and multimatic API) and hopefully bring more stable servers: https://myvaillant.com/. Migration should already be started, but I don't have any info from the community

**Comment by hvbargen** [comment]
Thx, I am going to try that PR (101).

**Comment by hvbargen** [comment]
Feedback after using @xaviergriffon's PR for a couple of days:

To be more precise, I forked this repository and the pymultiMATIC repository and pulled Xavier's branches:
For the pymultiMATIC repo, I'm on the senso_app branch (7dfbacf: "upgrade version to 0.7.0b1 for vaillant-component dependency").
For the vaillant-component, I'm on the master branch (3854e8b: "Senso compatibility").

I'm not quite sure if I set it up correctly in HACS.  In the custom repositories, it's showing my repo and the 3854e8b version.
So the vaillant-component itself is probably correct, but I'm not sure if the vaillant-component also uses the patched pymultiMATIC - I don't understand where and how this dependency is defined.

Anyway, it seems to be working fine, with the following exceptions:

1) Similar to what is described in #157 and #135, the total power consumption update rate seems somewhat strange.

2) Nothing happens when I click on the green time program button:
![image](https://user-images.githubusercontent.com/37015738/216813163-eeaac929-6734-477a-9104-b0785d6b7327.png)
ATM nothing happens, but yesterday this resulted in an error message popping up in the UI (on the mobile app).
What should happen when I click the button?

3) This diagram seems to be useful. But what does it show exactly? Where can I find an explanation?
My assumption is:
Blue line: What the temperature is (from the SensoComfort temperature sensor)
Violet line: Target temperature according to the time program
Orange area: Heat pump is heating??
![image](https://user-images.githubusercontent.com/37015738/216812892-2ea6e17a-37b6-4eba-9d9a-90bb48b3acdc.png)

**Comment by thomasgermain** [comment]
I didn't have to yet to test new senso app compatibility.

For point 3, the diagram is the vanilla HA diagram:
- blue: current temperature
- violet: target temperature
- orange area: where the zone is actually heated. (There is a field in the API, which indicate if the zone is heatin or not)

**Comment by xaviergriffon** [comment]
For point 2, the time program button is used to switch to automatic mode.
For example, when you switch to Quick Veto via the gauge, the button is greyed out :
![image](https://user-images.githubusercontent.com/5923066/217015860-43e8c085-2d18-464e-b7d6-1ec4a525df8a.png)
After pressing, it turns green to indicate the mode.
![image](https://user-images.githubusercontent.com/5923066/217016610-0d4f6a55-273c-41c8-ad5d-c34563a7ee32.png)
