### ISSUE TITLE
warm water circulation

### ISSUE THREAD

**Issue by feldi59** [thomasgermain/vaillant-component#217]
Hi, is it possible to start and stop the warm water circulation with your implemention?
Sorry this is just a question, but i really do not know where to place it.

**Comment by thomasgermain** [comment]
Hello, no there is no why to do it currently

**Comment by Waschbeton** [comment]
I struggled with the same problem a couple of weeks ago since I wanted to produce hot water when my pv system was producing to much energy. Filling the hot water tank and overwriting the original multi Matic schedules is done with temperature changes and / or the quick veto service. I found out that the quick veto "one day at home" overwrites everything including the pump. So in my opinion you could probably call the service to activate "one day at home" and with a short delay change all other Options like ventilation, hot water and heating to the desired settings?
This is my hot water schedule 
![Screenshot_20231002-112021](https://github.com/thomasgermain/vaillant-component/assets/46159198/e7f016b9-d0c1-489a-be7a-a19b7b97d7ea)

This is my circulation pump schedule 
![Screenshot_20231002-112000](https://github.com/thomasgermain/vaillant-component/assets/46159198/b5a32057-08ae-4e6a-b036-16b5a70480be)
This is how it looks like with the automation running 
![Screenshot_20231002-113328](https://github.com/thomasgermain/vaillant-component/assets/46159198/2dbed9f3-f687-49eb-a4ac-52675e3e045d)

This is the automation. If battery is full for more than 25 minutes and more than 1kwh is going to grid it will activate the hot water. Deactivation is handeld in another automation 
``
Alias: "Heißes Wasser bei voller Batterie "
description: ""
trigger:
  - type: battery_level
    platform: device
    device_id: aad347181b9d96eb458b998c3b44eee7
    entity_id: 70875f083b3763dacd268984a2194c5b
    domain: sensor
    above: 99
    for:
      hours: 0
      minutes: 25
      seconds: 0
condition:
  - condition: numeric_state
    entity_id: sensor.leistung_netz
    below: 1000
action:
  - service: multimatic.set_quick_mode
    data:
      quick_mode: QM_ONE_DAY_AT_HOME
      duration: 1
  - service: water_heater.set_temperature
    data:
      temperature: 65
    target:
      entity_id: water_heater.control_dhw
mode: single
``
