### ISSUE TITLE
Error: 403, message='Forbidden'

### ISSUE THREAD

**Issue by doubleninja** [thomasgermain/vaillant-component#271]
I have the following error in the log.
In addition, some entities are no longer available, e.g. consumed_electrical_energy_domestic_hot_water or heating_energy_efficiency
I have homeassistant version:
Core: 2024.3.0
Operating System: 12.0

Logger: myPyllant.api
Quelle: /usr/local/lib/python3.12/site-packages/myPyllant/api.py:1091
Erstmals aufgetreten: 11:49:11 (1 Vorkommnisse)
Zuletzt protokolliert: 11:49:11

Could not get diagnostic trouble codes
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 1086, in get_diagnostic_trouble_codes
    response = await self.aiohttp_session.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 691, in _request
    await raise_for_status(resp)
  File "/usr/local/lib/python3.12/site-packages/myPyllant/http_client.py", line 50, in on_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/88c0eb4e-2a80-4a3a-862a-fe9383e6ec45/diagnostic-trouble-codes')

**Comment by thomasgermain** [comment]
Hello,

I made a communication here: https://community.home-assistant.io/t/vaillant-multimatic-integration/87240/562.

This integration will work until you migrate, after that you will have to switch to the new integration (it requires some maintenance, since the system is quite different from multimatic).

For now, ambisense it not yet integrated, but I'm busy with @signalkraft
