### ISSUE TITLE
MultiMatic app end-of-life. Is successor myVAILLANT-app compliant with your vaillant-component?

### ISSUE THREAD

**Issue by johanvh83** [thomasgermain/vaillant-component#272]
Hi Thomas,
I received an email from Vaillant that my existing MultiMatic app will no longer work after 1th of April 2024 and will be replaced by a new myVAILLANT app.
When I download the new app I have to confirm that the system only will work with the new application so I was wondering if my HA with your vaillant-componet will remain working.
Can you please clarify how to proceed.
So far I haven't confirmed to use the new myVAILLANT app.

**Comment by thomasgermain** [comment]
Hello,

I made a communication here: https://community.home-assistant.io/t/vaillant-multimatic-integration/87240/562.

This integration will work until you migrate, after that you will have to switch to the new integration (it requires some maintenance, since the system is quite different from multimatic).

For now, ambisense it not yet integrated, but I'm busy with @signalkraft
