### ISSUE TITLE
received my ambisense modules yesterday: getting error when adding integration

### ISSUE THREAD

**Issue by lecocqe** [thomasgermain/vaillant-component#74]
![image](https://user-images.githubusercontent.com/18657222/124384707-da618880-dcd2-11eb-9d96-19e221388b2d.png)
hello, i added 2 VR50 modules into my config. now i'm getting this error when adding integration...

**Comment by lecocqe** [comment]
I deleted all the old data. deleted from HACS. rebooted. adding via HACS...

**Comment by thomasgermain** [comment]
... and is it working ?

**Comment by lecocqe** [comment]
no, always same message...

**Comment by thomasgermain** [comment]
Is the app working ? could you run this script ?:
- for windows powershell: https://github.com/thomasgermain/pymultiMATIC/blob/master/script/print_response.ps1
`./print_response.ps1 user password {zones_urls}`

- or for linux: https://github.com/thomasgermain/pymultiMATIC/blob/master/script/print_response.sh:
`sh print_response.sh user password {zones_urls}`

It sounds like the API is still updating your system

**Comment by lecocqe** [comment]
{"errorCode":"INVALID_PARAMS"}

app is ok . i have the same impression

**Comment by lecocqe** [comment]
[ambisenseTest_20210704_1029_anonimzed.txt](https://github.com/thomasgermain/vaillant-component/files/6759923/ambisenseTest_20210704_1029_anonimzed.txt)
Full response

**Comment by thomasgermain** [comment]
You are using the 1.7.0b3 right ?

It's strange because you can get your zones through `/system` endpoint but not through `/zones` endpoint :unamused:.

Just to be sure, you received 
```
{"errorCode":"INVALID_PARAMS"}
```
while calling `https://smart.vaillant.com/mobile/api/v4/facilities/{serial}/systemcontrol/v1/zones` ?

Maybe this is not possible to get zones because in your case, you have only one zone, which is now "converted" to multiple rooms and the zone itself doesn't appear anymore in the app (am I right ?)

I can ignore error 400 while setuping the integration but it seems odd, because I would not know if this is a real error at the integration  side or just somehow bad return code (the API is used to return HTTP 409 when something is not present in the system).

Anyway, I would like to wait a bit, as I said, maybe there is something updating behind the scene or so.

**Comment by lecocqe** [comment]
1.7.0b3, yes
yes: {"errorCode":"INVALID_PARAMS"}
yes: no zone anymore in app. and now 2 rooms correctly displayed in app.

i also rebooted phone. reinstalled APP. delete app cache.... to try to force update if necessary. but nothing worked. :(
![image](https://user-images.githubusercontent.com/18657222/124400823-afeceb00-dd25-11eb-8c24-adc9f61ce172.png)

**Comment by lecocqe** [comment]
this morning, system is suddendly ok. 
the only thing is that i have all devices twice and i don't know how to delete the ones that are not used.

**Comment by thomasgermain** [comment]
Ok sounds good.

Maybe some devices change their id because of the new ambisense system. I guess you can delete the instance of the integration et re-add it (just from the UI, no need to delete custom_component etc.)

**Comment by lecocqe** [comment]
ok. thank you for your help.
