### ISSUE TITLE
RecoVair not seen in Multimac & Ventilation Entity Day/Night shows up as ON/OFF

### ISSUE THREAD

**Issue by VaillantHassIo** [thomasgermain/vaillant-component#80]
Hello Thomas,

i am glad you integrated/created this multimac app for HA. Thanks for that!

I’ve installed version 1.7.0 without using a serial number and 4 entities show up for my Vaillant VWF 58/4 LWWP ( Heizkreis, Warmwasser, Multimac, VR921 ) I am missing the device for my recoVAIR which is visible in the MultiMac App.

Also the entity ventilator is visible and adding it to the dashboard it seems that ON responds to DAY and OFF responds to NIGHT, which could be improved i guess.

Picture Ventilation ( NIGHT ) shown aus OFF ( 'AUS' )

![image](https://user-images.githubusercontent.com/87522613/125945737-6ac3ed74-2aaf-42a7-ab55-e1ef9bef84f0.png)

Picture of Integration 4 Devices and 11 Entities found

![image](https://user-images.githubusercontent.com/87522613/125946002-7e312939-4889-4047-91e8-b680ccb5fba9.png)

Rgds
Mike

**Comment by VaillantHassIo** [comment]
i guess the ventilator 'issue' is already been disucssed in https://github.com/thomasgermain/vaillant-component/issues/33

so just leaves my questions, if the recoVAIR should be detected as a own device

**Comment by thomasgermain** [comment]
Hello,

what do you mean by "missing recoVAIR device" ? What are you expecting ?

Issue #33 is different: DAY mode <> DAY level. DAY mode is the mode the ventilation is running, DAY level is "how fast" the ventilation occurs (level is between 1 and 6).

Normally, you can chose a `preset` between DAY, NIGHT and AUTO (= the vaillant modes, available in the app)
Then these presets are mapped to HA (which only have ON and OFF for ventilation). So I considered AUTO and DAY = ON and NIGHT = OFF.

According to the doc, (I rely on the doc, because I don't have any ventilation) you can only set AUTO, COMFORT (which is, behind the scene, DAY) and SET BACK (which is behind the scene NIGHT)

**Comment by VaillantHassIo** [comment]
Hello Thomas, thanks for the reply.

I would have assumed that the recovair is discovered as a separate device holding the ventilation entity .. but i guess this is not how it works. I am fairly new to HA.

If you need me to test anything in regards to the recovair let me know ;) i am happy to help oterhwise i think this issue can be closed.

**Comment by thomasgermain** [comment]
Well yeah, can understand about the device, but actually there is nothing available in the API in order to create a device.

Let me know if you have other issues (specially with ventilation, since I cannot test it myself).
