### ISSUE TITLE
Energy Management - Consumption Sensors

### ISSUE THREAD

**Issue by pfriedrich84** [thomasgermain/vaillant-component#84]
Hi Thomas,

as I'm sure you know already, Home Assistant is going into direction of Energy Management:
https://www.home-assistant.io/blog/2021/08/04/home-energy-management/

I think this is an AWESOME move and i would like to add our multimatic as a single consumer device, therefore an energy meter sensos is needed:
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

We have the consumption inside the APP (VWF 87/4) seperated by Heating, Cooling and Water Heater.
Is there any chance to get this out of the API?

Also willing to help by debugging my Account ... ;-)

Cheers, 
Paul

**Comment by thomasgermain** [comment]
Hi Paul,

thanks for the suggestion, this is somehow duplicated of #32.

I just started looking at it. I don't have any emf reports available, so I'm kind of blind for this one. 

I still have to dig what value I have to provide to HA in order to by "energy" compatible. I think, by default, vaillant is providing daily values for all reports in one single API call (which is quite easy to handle). But I think homeassistant requires a overall total value (bwt, do you know ?).  And to get this total value, I have to do one API call per report (and you could have ~10 reports), which is a bit harder to handle.

Anyway, I'm looking at it, so I hope I can provide something useful.


Cheers,

Thomas

**Comment by pfriedrich84** [comment]
Hi Thomas,
i can help with the target as i played around it a bit already! ;-) This example of a sensor of mine is working:
state_class: measurement
last_reset: '1970-01-01T00:00:00+00:00'
unit_of_measurement: kWh
friendly_name: Server-Schrank [kWh]
device_class: energy

The value is just always increasing and never reseted (total consumption).
The Energy Implementation of HomeAssistant is now showing those 4-5kwh on a daily basis. Depends on usage/Backup-Tasks/VMs etc - so its automatically splitting it based on the daily increase ... :)

Hope this helps!

Cheers,
Paul
