### ISSUE TITLE
No control entities are selectable/visible on HA just input information.

### ISSUE THREAD

**Issue by TheJokerHA** [thomasgermain/vaillant-component#96]
My Vaillant setup is the following:

    VIH QW 190/6 with VWL 75/6 A 230V S2 heating system
    VR921
    VRC721
    SensoAPP

I have tried the new release 1.9 of your integration on my HA its just creating input/data/sensor entities.
Missing all control [entities.

Attached:

    Relevant HA log and HA screenshots
    App SensoAPP screenshots

[HA.txt](https://github.com/thomasgermain/vaillant-component/files/7164387/HA.txt)
![Screenshot_20210914-203602_sensoAPP](https://user-images.githubusercontent.com/85641621/133315933-c19917f4-6039-4791-beda-7efe3764d266.jpg)
![Screenshot_20210914-203612_sensoAPP](https://user-images.githubusercontent.com/85641621/133315937-ed187236-23d6-4543-87b5-d5deb1937494.jpg)
![Screenshot_20210914-203620_sensoAPP](https://user-images.githubusercontent.com/85641621/133315941-88a1bdb1-ecbd-47b7-9047-1cbf80145f87.jpg)
![Screenshot_20210914-203627_sensoAPP](https://user-images.githubusercontent.com/85641621/133315943-0c15541f-955e-44bb-9754-f2a73f450945.jpg)
[home-assistant.log](https://github.com/thomasgermain/vaillant-component/files/7164391/home-assistant.log)

**Comment by thomasgermain** [comment]
Hello,

unfortunately, sensoAPP is not supported :confused:, only multimatic is. It may work in some case, like in your case, but some part of the API are not exactly the same as multimatic.

There is no plan to support it since myVaillant will get released soon and it should unify all vaillant api. Here is a link about it (their communication is a nightmare.. information is not exactly the same depending on the language..). You have some kind of roadmap in german version. https://upgrade.myvaillant.com/
